pop_accounts/urls.py
from django.urls import path
from . import views
from .views import (EmailCheckView, RegisterView, Login2FAView, VerifyEmailView, PastPurchaseView,
                    UserLogOutView, UserDashboardView, Verify2FACodeView, AccountDeletedView,
                    UserInterestedInView, MarkProductInterestedView, MarkProductOnNoticeView, 
                    UserOnNoticeView, OpenBidsView, AdminInventoryView, EnRouteView, AddProductsView,
                    UpdateProductView, CompleteProfileView, PersonalInfoView, GetAddressView, PastBidView,
                    DeleteAddressView, SetDefaultAddressView, DeleteAccountView, UserPasswordResetConfirmView,
                    ShippingTrackingView, UserOrderPager, AdminDashboardView, SalesView, MostOnNotice, 
                    MostInterested, TotalOpenBidsView, TotalAccountsView, AccountSizesView, 
                    PendingOkayToShipView, PendingOrderShippingDetailView, UpdateShippingView, 
                    GetOrderShippingDetail, UpdateShippingPostView, ViewShipmentsView, AddProductsGetView,
                    Resend2FACodeView, SendPasswordResetLink, SocialLoginCompleteView)

app_name = 'pop_accounts'
urlpatterns = [

    # Auth register / login class based views
    path('auth/check-email/', EmailCheckView.as_view(), name='check_email'),
    path('auth/register/', RegisterView.as_view(), name='register'),
    path('verify/<uidb64>/<token>/', VerifyEmailView.as_view(), name='verify_email'),
    path('auth/user-login/', Login2FAView.as_view(), name='user_login'),

    # Social Auth / Social Login
    path('auth/complete-profile/', CompleteProfileView.as_view(), name='complete_profile'),
    path('social-login-complete/', SocialLoginCompleteView.as_view(), name='social_login_complete'),
    path('get-user-info/', views.get_user_info, name="get_user_info"),

    
    # Auth register / login
    path('auth/verify-code/', Verify2FACodeView.as_view(), name='verify_2fa'),
    path('auth/send-reset-link/', SendPasswordResetLink.as_view(), name='send_reset_link'),
    path('resend-code/', Resend2FACodeView.as_view(), name='resend_2fa_code'),
    path('password-reset/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('logout/',UserLogOutView.as_view(), name='logout'),
       
    # path('place-bid/', DashboardPlaceBidView.as_view(), name='place_bid'),

    # User Info
    path('dashboard/', UserDashboardView.as_view(), name='dashboard'),
    path('personal-information/', views.PersonalInfoView.as_view(), name='personal_info'),
    path('delete-account/', DeleteAccountView.as_view(), name='delete_account'),
    path('account-deleted/', AccountDeletedView.as_view(), name='account_deleted'),    
    path('get-address/<uuid:address_id>/', GetAddressView.as_view(), name='get_address'),
    path('delete-address/<uuid:address_id>/', DeleteAddressView.as_view(), name='delete_address'),
    path('set-default-address/<uuid:address_id>/', SetDefaultAddressView.as_view(), name='set_default_address'),
    path('interested-in/', UserInterestedInView.as_view(), name='interested_in'),
    path('mark-interested/', MarkProductInterestedView.as_view(), name='mark_interested'),
    path('on-notice/', UserOnNoticeView.as_view(), name='on_notice'),
    path('mark-on-notice/', MarkProductOnNoticeView.as_view(), name='mark_on_notice'),
    path('open-bids/', OpenBidsView.as_view(), name="open_bids"),
    path('bids-history/', PastBidView.as_view(), name='past_bids'),
    path('purchase-history/', PastPurchaseView.as_view(), name='past_purchases'),
    path('shipping-tracking/', ShippingTrackingView.as_view(), name='shipping_tracking'),
    path('customer-order/<uuid:order_id>/', UserOrderPager.as_view(), name='customer_order'),

    # admin dashboard
    path('dashboard-admin/', AdminDashboardView.as_view(), name='dashboard_admin'),
    path('inventory-admin/', AdminInventoryView.as_view(), name='inventory_admin'),
    path('inventory-admin/<slug:slug>/', AdminInventoryView.as_view(), name='inventory_admin'),
    path('sales-admin/', SalesView.as_view(), name='sales_admin'),
    path('most-on-notice-admin/', MostOnNotice.as_view(), name='most_on_notice'),
    path('most-interested-admin/', MostInterested.as_view(), name='most_interested'),
    path('total-open-bids-admin/', TotalOpenBidsView.as_view(), name='total_open_bids'),
    path('total-accounts-admin/', TotalAccountsView.as_view(), name='total_accounts'),
    path('account-sizes-admin/', AccountSizesView.as_view(), name='account_sizes'),
    path('pending-okay-to-ship/', PendingOkayToShipView.as_view(), name='pending_okay_to_ship'),
    path('get-pending-order-shipping-detail/<uuid:order_no>/', PendingOrderShippingDetailView.as_view(), name='get_order_details'),

    path('update-shipping-admin/', UpdateShippingView.as_view(), name='update_shipping'),
    path('update-shipping-admin/<int:shipment_id>/', UpdateShippingPostView.as_view(), name='update_shipping_post'),
    path('get-shipping-detail/<int:shipment_id>/', GetOrderShippingDetail.as_view(), name='get_shipping_detail'),

    path('shipments-admin/', ViewShipmentsView.as_view(), name='shipments'),
    path('dashboard-en-route/', EnRouteView.as_view(), name='enroute'),
    path('dashboard-en-route/<slug:slug>/', EnRouteView.as_view(), name='enroute'),

    # admin dashboard | Adding products
    path('add-products-admin/', AddProductsView.as_view(), name='add_products'),
    path('add-products-admin/<int:product_type_id>/', AddProductsGetView.as_view(), name='add_products_get'),

    # admin dashboard | Updating products
    path('update-product-admin/', UpdateProductView.as_view(), name='update_product'),
    path('update-product-admin/<int:product_id>/', UpdateProductView.as_view(), name='update_product_detail'),
    # path('get-product-detail/<int:product_id>/<int:product_type_id>/', ProductDetailView.as_view(), name='get_product_detail'),
    # path('update-product-post/<int:product_id>/', UpdateProductPostView.as_view(), name='update_product_post'),



    # path('update-product-admin/<int:product_id>/', views.update_product_post, name='update_product_post'),
    # path('get-product-detail/<int:product_id>/', views.get_order_product_detail, name='get_product_detail'),

    

]

pop_up_auction/urls.py
from django.urls import path
from . import views
from .views import (PlaceBidView, AllAuctionView, ProductAuctionView, ProductsView, 
                    ComingSoonView, FutureReleases, ProductDetailView)

app_name = 'pop_up_auction'
urlpatterns = [
    path('', AllAuctionView.as_view(), name="auction"),
    path('place-bid/', PlaceBidView.as_view(), name='place_bid'),
    path('open/', ProductAuctionView.as_view(), name='product_auction'),
    path('open/<slug:slug>/', ProductAuctionView.as_view(), name='product_auction'),
    # path('product-buy/', ProductBuyView.as_view(), name='product_buy'),
    path('products/', ProductsView.as_view(), name='products'),
    path('products/<slug:slug>/', ProductsView.as_view(), name='products'),
    path('coming-soon/', ComingSoonView.as_view(), name='coming_soon'),
    path('coming-soon/<slug:slug>/', ComingSoonView.as_view(), name='coming_soon'),
    path('future-releases/', FutureReleases.as_view(), name='future_releases'),
    path('future-releases/<slug:slug>/', FutureReleases.as_view(), name='future_releases'),
    path('<slug:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('past-product-details/<int:item_id>/', views.past_product_detail, name='past_product_details'),
    path('past-bids-product-detail/<int:product_id>/', views.past_bid_product_detail_by_product, name='past_bids_product_detail')
   
]

pop_up_cart/urls.py
from django.urls import path
from . import views

app_name = 'pop_up_cart'

urlpatterns = [
    path('', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update')
]

pop_accounts/templates/pop_accounts/user_accounts/dashboard_pages/account_deleted.html
{% extends "layout.html" %}
{% load static %}


{% block title %}
Account Deleted
{% endblock %}

{% block main %}
<div class="section_container">
    <div class="page_title">
        <h2>Account Deleted</h2>
    </div>
    <div class="account_deleted_container">
        <h2>You're account has been deleted.</h2>
        <h3>We hate to see you go <span class="large_emoji">🥹</span></h3>
        <h3>May the universe smile upon you <span class="large_emoji">❤️</span></h3>
    </div>
</div>
{% endblock %}

pop_accounts/templates/pop_accounts/user_accounts/dashboard_pages/interested_in.html
{% extends "layout.html" %}
{% load static %}


{% block title %}Interested In{% endblock %}

{% block main %}

<div class="section_container">
    <div class="page_title">
        <h2>{{ user_intested_in_copy.page_title }}</h2>
    </div>
    <div class="interested_in_container">
        <div class="interested_in_open_bids_container">
            <div class="interested_in_databox_headers">
                {% for i in user_intested_in_copy.interested_in_headers %}
                <h3>{{ i.headers }}</h3>
                {% endfor %}
            </div>
            <div class="interested_in_open_bids">
                {% for p in prod_interested_in %}
                <div class="interested_in_items_container" id="int-product-{{ p.id }}">
                    <div class=" interested_in_year">
                        <p>{{ product_specifications.model_year }}</p>
                    </div>
                    <div class="interested_in_item">
                        <a href="product-details">
                            <p>{{ p.product_title }} {{ p.secondary_product_title }}</p>
                        </a>
                    </div>
                    <div class="interested_in_size">
                        {% if product_specifications.size %}
                        {% if product_specifications.product_sex == "Male" %}
                        <p>U.S. {{"Men's"}} {{product_specifications.size }}</p>
                        {% else %}
                        <p>U.S. {{"Women's"}} {{product_specifications.size }}</p>
                        {% endif %}
                        <p> - </p>
                        {% endif %}
                    </div>
                    <div class="interested_in_condition">
                        <p>{{product_specifications.condition|capfirst }}</p>
                    </div>
                    <div class="interested_in_condition">
                        <input type="checkbox" class="interested_checkbox" data-product-id="{{ p.id }}" checked></input>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    {% endblock %}

pop_accounts/templates/pop_accounts/user_accounts/dashboard_pages/on_notice.html
{% extends "layout.html" %}
{% load static %}


{% block title %}On Notice{% endblock %}

{% block main %}

<div class="section_container">
    <div class="page_title">
        <h2>{{ user_on_notice_copy.page_title }}</h2>
    </div>
    <div class="interested_in_container">
        <div class="interested_in_open_bids_container">
            <div class="interested_in_databox_headers">
                {% for i in user_on_notice_copy.on_notice_headers %}
                <h3>{{ i.headers }}</h3>
                {% endfor %}
            </div>
            <div class="interested_in_open_bids">
                {% for prod in prods_on_notice_for %}
                <div class="interested_in_items_container" id="notice-product-{{ prod.id }}">
                    <div class=" interested_in_year">
                        <p>{{ product_specifications.model_year }}</p>
                    </div>
                    <div class="interested_in_item">
                        <a href="product-details">
                            <p>{{ prod.product_title }} {{ prod.secondary_product_title }}</p>
                        </a>
                    </div>
                    <div class="interested_in_size">
                        {% if product_specifications.size %}
                        {% if product_specifications.product_sex == "Male" %}
                        <p>U.S. {{"Men's"}} {{product_specifications.size }}</p>
                        {% else %}
                        <p>U.S. {{"Women's"}} {{product_specifications.size }}</p>
                        {% endif %}
                        <p> - </p>
                        {% endif %}
                    </div>
                    <div class="interested_in_condition">
                        <p>{{product_specifications.condition|capfirst }}</p>
                    </div>
                    <div class="interested_in_condition">
                        <input type="checkbox" class="interested_checkbox" data-product-id="{{ prod.id }}"
                            checked></input>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    {% endblock %}

pop_accounts/templates/pop_accounts/user_accounts/dashboard_pages/open_bids.html
{% extends "layout.html" %}
{% load static %}
{% load custom_math %}
{% load email_filters %}
{% load humanize %}

{% block title %}
Auction
{% endblock %}

{% block main %}

<div class="section_container">
    <div class="page_title">
        <h2>{{ user_open_bids_copy.page_title }}</h2>
    </div>
    <div class="interested_in_container">
        <div class="interested_in_open_bids_container">
            <div class="interested_in_databox_headers">
                {% for i in user_open_bids_copy.open_bids_headers %}
                <h3>{{ i.headers }}</h3>
                {% endfor %}
            </div>
            <div class="open_bids_open_bids">
                {% for hb in open_bids %}
                <div class="open_bids_items_container">
                    <div class="open_bids_detail_item">
                        <a href="product-details">
                            <p>{{ hb.product }} {{ hb.product.secondary_product_title }}</p>
                        </a>
                    </div>
                    <div class="open_bids_detail_size">
                        {% for gen in hb.specs|slice:"5:6" %}
                        {% if gen.value == "Male" %}

                        <p>U.S. {{"Men's"}}
                            <span>
                                {% for h in hb.specs|slice:"4:5" %}
                                {{ h }}
                                {% endfor %}
                            </span>
                        </p>
                        {% else %}
                        <p>U.S. {{"Womens's"}}
                            <span>
                                {% for h in hb.specs|slice:"4:5" %}
                                {{ h }}
                                {% endfor %}
                            </span>
                        </p>
                        {% endif %}
                        {% endfor %}
                    </div>
                    <div class="open_bids_last_bid">
                        <p>${{ hb.highest_user_bid.amount }}</p>
                    </div>
                    <div class="open_bids_bid_status">
                        {% if hb.highest_user_bid.amount == hb.current_highest %}
                        <p>Current Top Bid</p>
                        {% else %}
                        <p>Losing Bid</p>
                        {% endif %}
                    </div>
                    <div class="indi_bids_action">
                        {% if hb.highest_user_bid.amount != hb.current_highest %}
                        <button id="opeBidsBidButton" class="button_medium bidButtonClass"
                            data-product-id="{{ hb.product.id }}">Increase Bid</button>
                        {% endif %}
                    </div>
                    <!-- Bid Modal -->
                    <div class="modal fade" id="bidModal-{{ hb.product.id }}" tabindex="-1"
                        aria-labelledby="bidModalLabel" aria-hidden="true">
                        <div class="modal_content">

                            <div class="modal_header">
                                <h3 class="modal-title" id="bidModalLabel">Increase Your Bid</h3>
                                <button type="button" class="btn-close closeModal" aria-label="Close">X</button>
                            </div>
                            <div class="modal_bid_shipping_days_left">
                                <div class="modal_bid_and_shipping">
                                    <h5>${{ hb.current_highest }}</h5>
                                    <h5> + Shipping</h5>
                                </div>
                                <div class="modal_bid_numb_of_bids">
                                    <h5><span>{{ hb.bid_count }}</span>bids</h5>
                                </div>
                                <div class="modal_bid_days_left">
                                    {% if hb.duration.days > 1 %}
                                    <h5><span>{{ hb.duration.days }}</span>days left</h5>
                                    {% else %}
                                    <h5><span>{{ hb.duration.days }}</span>day left</h5>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="modal_body">
                                <form class="bidForm" id="bidForm-{{ hb.product.id }}" method="post"
                                    data-product-id="{{ hb.product.id }}" action="{% url 'pop_up_auction:place_bid' %}">
                                    {% csrf_token %}
                                    <div id="predefined_bids-{{ hb.id }}" class="predefined_bids"
                                        data-product-id="{{ hb.product.id }}">
                                        {% if hb.current_highest %}
                                        {% for inc in quick_bid_increments %}
                                        {% with new_bid=hb.current_highest|compute_number:inc %}
                                        <button type="button" data-amount="{{ new_bid }}"
                                            class="button_long_small quick_bid">Bid <span>
                                                ${{new_bid|intcomma }}.00</span></button>
                                        {% endwith %}
                                        {% endfor %}
                                        {% endif %}
                                        <button class="button_long_small">Cancel Bids</button>
                                    </div>

                                    <div class="bid_modal_input_container">
                                        <input type="hidden" name="product_id" value="{{ hb.product.id }}">
                                        <label for="custom_bid"><span>or enter your bid</span></label>
                                        <div class="modal_bid_input_submit_btn">
                                            <div class="outer_input_container">
                                                <h4>$</h4>
                                                <input type="number" step="0.01" id="custom_bid-{{ hb.product.id }}"
                                                    name="bid_amount" class="form-control" required
                                                    min="{{ hb.current_highest|compute_number:1|intcomma}}.00"
                                                    placeholder="Enter custom bid">
                                            </div>
                                            <div class="mt-3">
                                                <button type="submit" class="btn button_long_small"
                                                    id="submitBid-{{ hb.product.id }}">Submit
                                                    Bid</button>
                                            </div>
                                        </div>
                                        {% if hb.current_highest %}
                                        <p class="bid_hint">Enter
                                            <span>${{hb.current_highest|compute_number:1|intcomma}}.00</span>
                                            or more
                                        </p>
                                        {% else %}
                                        <p class="bid_hint">Enter
                                            <span>${{hb.retail_price|compute_number:1|intcomma}}.00</span>
                                            or more
                                        </p>
                                        {% endif %}
                                    </div>
                                </form>
                                <div class="bid_response" style="color:red"></div>
                            </div>
                            <div class="modal_user_abbr_user_info">
                                <div class="modal_user_pay_email_shipping_container">

                                    {% for image in hb.product_image.all %}
                                    {% if image.is_feature %}
                                    <img class="modal_user_card_img" src="{{ image.image.url }}" alt="Responsive Image">
                                    {% endif %}
                                    {% endfor %}

                                    {% if user.is_authenticated %}
                                    <p>{{ user.email|obfuscate_email }}</p>
                                    {% endif %}
                                    {% for address in addresses %}
                                    <p>ship to <span>{{ address.postcode }}</span></p>
                                    {% endfor %}
                                </div>
                                <div class="modal_user_info_update_container">
                                    <a href="/">Update</a>
                                </div>
                            </div>
                            <div class="modal_purchase_disclaimer">
                                <p>
                                    By selecting to submit bid, you authorize The Pop Up to bid up to
                                    your max
                                    bid and if
                                    you win, charge your bid amount and related costs to your
                                    <span>PayPal</span> account.
                                    You also agree to The Pop Up's User Agreement and Privacy Notice.
                                </p>
                            </div>
                        </div>
                    </div>
                    <!-- End of Bid Modal -->
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endblock %}

pop_accounts/templates/pop_accounts/user_accounts/dashboard_pages/past_bids.html
{% extends "layout.html" %}
{% load static %}


{% block title %}
Past Bids
{% endblock %}

{% block main %}

<div class="section_container">
    <div class="page_title">
        <h2>{{ user_past_bids_copy.page_title }}</h2>
    </div>
    <div class="interested_in_container">
        <div class="interested_in_open_bids_container">
            <div class="interested_in_databox_headers">
                {% for i in user_past_bids_copy.past_bids_headers %}
                <h3>{{ i.headers }}</h3>
                {% endfor %}
            </div>
            <div class="interested_in_open_bids">
                {% for bid in bid_history %}
                <div class="interested_in_items_container">
                    <div class="interested_in_year">
                        <p>{{ bid.bid_time|date:"F d, Y"}}</p>
                    </div>
                    <div class="interested_in_item">
                        <a href="{% url 'pop_up_auction:past_bids_product_detail' bid.product.id%}">
                            <p>{{ bid.mptt_specs.model_year }} {{ bid.product.product_title }} <br>
                                {{ bid.product.secondary_product_title }}
                            </p>
                        </a>
                    </div>
                    <div class="interested_in_size">
                        {% if bid.mptt_specs.product_sex == "Male" %}
                        <p>{{ bid.mptt_specs.size }} US Mens</p>
                        {% elif bid.mptt_specs.product_sex == "Female" %}
                        <p>{{ bid.mptt_specs.size }} US Womens</p>
                        {% else %}
                        <p>N/A</p>
                        {% endif %}
                    </div>
                    <div class="interested_in_condition">
                        <p>${{bid.bid_amount}}</p>
                    </div>
                    <div class="interested_in_condition">
                        {% if bid.is_winning == True %}
                        <p>Winning Bid</p>
                        {% else %}
                        <p>Losing Bid</p>
                        {% endif %}
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

pop_accounts/templates/pop_accounts/user_accounts/dashboard_pages/past_purchases.html
{% extends "layout.html" %}
{% load static %}


{% block title %}
Past Purchases
{% endblock %}

{% block main %}

<div class="section_container">
    <div class="page_title">
        <h2>{{ user_past_purchase_copy.page_title }}</h2>
    </div>
    <div class="interested_in_container">
        <div class="interested_in_open_bids_container">
            <div class="past_purchases_databox_headers">
                {% for i in user_past_purchase_copy.past_purchases_headers %}
                <h3>{{ i.headers }}</h3>
                {% endfor %}
            </div>
            <div class="past_purchases_inner_container">
                {% for order in orders %}
                <div class="past_purchases_items_container">
                    <div class="interested_in_item">
                        {% for item in order.items.all %}
                        <a href="{% url 'pop_up_auction:past_product_details' item.id %}">
                            <p>{{ item.product_title }} <br> {{ item.secondary_product_title}}</p>
                        </a>
                        {% endfor %}
                    </div>
                    <div class="interested_in_size">
                        <p>{{ order.created_at|date:"F d, Y"}}</p>
                    </div>
                    <div class="interested_in_item">
                        <a href="{% url 'pop_accounts:customer_order' order.id%}">
                            <p>{{ order.id}}</p>
                        </a>

                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

pop_accounts/templates/pop_accounts/user_accounts/dashboard_pages/shipping_tracking.html
{% extends "layout.html" %}
{% load static %}


{% block title %}Shipping & Tracking{% endblock %}

{% block main %}

<div class="section_container">
    <div class="page_title">
        <h2>{{ user_shipping_copy.page_title }}</h2>
    </div>
    <div class="shipping_tracking_container">
        <div class="shipping_tracking_details_container">
            <div class="ship_and_track_databox_headers">
                {% for header in tracking_categories %}
                <h3>{{ header.header }}</h3>
                {% endfor %}

            </div>
            <div class="shipping_tracking_info_container">
                {% for shipment in shipments %}
                <div class="ship_track_items_container">
                    <div class=" interested_in_year">
                        <p>{{ shipment.shipment.tracking_number }}</p>
                    </div>
                    <div class="interested_in_item">
                        <a href="product-details">
                            <p>{{ shipment.shipment.shipped_at|date:"M d, Y"}}</p>
                        </a>
                    </div>
                    <div class="interested_in_size">
                        {{ shipment.shipment.carrier|upper }}
                    </div>
                    <div class="interested_in_condition">
                        <a href="{% url 'pop_accounts:customer_order' shipment.order_id%}">
                            {{ shipment.order_id }}</a>
                    </div>
                    <div class="interested_in_condition">
                        {% if shipment.shipment.delivered_at == None %}
                        {% if shipment.shipment.shipped_at %}
                        In Transit
                        {% endif %}
                        {% elif shipment.shipment.delivered_at %}
                        {{ shipment.shipment.delivered_at }}
                        {% endif %}
                    </div>
                    <div class="interested_in_condition">
                        <p>{{ shipment.shipping_address.town_city }} {{ shipment.shipping_address.state }}
                            {{ shipment.shipping_address.postcode }}
                        </p>
                    </div>
                </div>

                {% endfor %}
            </div>

        </div>
    </div>


    {% endblock %}