pop_accounts/urls.py
from django.urls import path
from . import views
from .views import (EmailCheckView, RegisterView, Login2FAView, VerifyEmailView, PastPurchaseView,
                    UserLogOutView, UserDashboardView, Verify2FACodeView, AccountDeletedView,
                    UserInterestedInView, MarkProductInterestedView, MarkProductOnNoticeView, 
                    UserOnNoticeView, OpenBidsView, AdminInventoryView, EnRouteView, AddProductsView,
                    UpdateProductView, CompleteProfileView, PersonalInfoView, GetAddressView, PastBidView,
                    DeleteAddressView, SetDefaultAddressView, DeleteAccountView, UserPasswordResetConfirmView,
                    ShippingTrackingView, UserOrderPager, AdminDashboardView, SalesView, MostOnNotice, 
                    MostInterested, TotalOpenBidsView, TotalAccountsView, AccountSizesView, 
                    PendingOkayToShipView, PendingOrderShippingDetailView, UpdateShippingView, 
                    GetOrderShippingDetail, UpdateShippingPostView, ViewShipmentsView, AddProductsGetView,
                    Resend2FACodeView, SendPasswordResetLink, SocialLoginCompleteView)

app_name = 'pop_accounts'
urlpatterns = [

    # Auth register / login class based views
    path('auth/check-email/', EmailCheckView.as_view(), name='check_email'),
    path('auth/register/', RegisterView.as_view(), name='register'),
    path('verify/<uidb64>/<token>/', VerifyEmailView.as_view(), name='verify_email'),
    path('auth/user-login/', Login2FAView.as_view(), name='user_login'),

    # Social Auth / Social Login
    path('auth/complete-profile/', CompleteProfileView.as_view(), name='complete_profile'),
    path('social-login-complete/', SocialLoginCompleteView.as_view(), name='social_login_complete'),
    path('get-user-info/', views.get_user_info, name="get_user_info"),

    
    # Auth register / login
    path('auth/verify-code/', Verify2FACodeView.as_view(), name='verify_2fa'),
    path('auth/send-reset-link/', SendPasswordResetLink.as_view(), name='send_reset_link'),
    path('resend-code/', Resend2FACodeView.as_view(), name='resend_2fa_code'),
    path('password-reset/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('logout/',UserLogOutView.as_view(), name='logout'),
       
    # path('place-bid/', DashboardPlaceBidView.as_view(), name='place_bid'),

    # User Info
    path('dashboard/', UserDashboardView.as_view(), name='dashboard'),
    path('personal-information/', views.PersonalInfoView.as_view(), name='personal_info'),
    path('delete-account/', DeleteAccountView.as_view(), name='delete_account'),
    path('account-deleted/', AccountDeletedView.as_view(), name='account_deleted'),    
    path('get-address/<uuid:address_id>/', GetAddressView.as_view(), name='get_address'),
    path('delete-address/<uuid:address_id>/', DeleteAddressView.as_view(), name='delete_address'),
    path('set-default-address/<uuid:address_id>/', SetDefaultAddressView.as_view(), name='set_default_address'),
    path('interested-in/', UserInterestedInView.as_view(), name='interested_in'),
    path('mark-interested/', MarkProductInterestedView.as_view(), name='mark_interested'),
    path('on-notice/', UserOnNoticeView.as_view(), name='on_notice'),
    path('mark-on-notice/', MarkProductOnNoticeView.as_view(), name='mark_on_notice'),
    path('open-bids/', OpenBidsView.as_view(), name="open_bids"),
    path('bids-history/', PastBidView.as_view(), name='past_bids'),
    path('purchase-history/', PastPurchaseView.as_view(), name='past_purchases'),
    path('shipping-tracking/', ShippingTrackingView.as_view(), name='shipping_tracking'),
    path('customer-order/<uuid:order_id>/', UserOrderPager.as_view(), name='customer_order'),

    # admin dashboard
    path('dashboard-admin/', AdminDashboardView.as_view(), name='dashboard_admin'),
    path('inventory-admin/', AdminInventoryView.as_view(), name='inventory_admin'),
    path('inventory-admin/<slug:slug>/', AdminInventoryView.as_view(), name='inventory_admin'),
    path('sales-admin/', SalesView.as_view(), name='sales_admin'),
    path('most-on-notice-admin/', MostOnNotice.as_view(), name='most_on_notice'),
    path('most-interested-admin/', MostInterested.as_view(), name='most_interested'),
    path('total-open-bids-admin/', TotalOpenBidsView.as_view(), name='total_open_bids'),
    path('total-accounts-admin/', TotalAccountsView.as_view(), name='total_accounts'),
    path('account-sizes-admin/', AccountSizesView.as_view(), name='account_sizes'),
    path('pending-okay-to-ship/', PendingOkayToShipView.as_view(), name='pending_okay_to_ship'),
    path('get-pending-order-shipping-detail/<uuid:order_no>/', PendingOrderShippingDetailView.as_view(), name='get_order_details'),

    path('update-shipping-admin/', UpdateShippingView.as_view(), name='update_shipping'),
    path('update-shipping-admin/<int:shipment_id>/', UpdateShippingPostView.as_view(), name='update_shipping_post'),
    path('get-shipping-detail/<int:shipment_id>/', GetOrderShippingDetail.as_view(), name='get_shipping_detail'),

    path('shipments-admin/', ViewShipmentsView.as_view(), name='shipments'),
    path('dashboard-en-route/', EnRouteView.as_view(), name='enroute'),
    path('dashboard-en-route/<slug:slug>/', EnRouteView.as_view(), name='enroute'),

    # admin dashboard | Adding products
    path('add-products-admin/', AddProductsView.as_view(), name='add_products'),
    path('add-products-admin/<int:product_type_id>/', AddProductsGetView.as_view(), name='add_products_get'),

    # admin dashboard | Updating products
    path('update-product-admin/', UpdateProductView.as_view(), name='update_product'),
    path('update-product-admin/<int:product_id>/', UpdateProductView.as_view(), name='update_product_detail'),
    # path('get-product-detail/<int:product_id>/<int:product_type_id>/', ProductDetailView.as_view(), name='get_product_detail'),
    # path('update-product-post/<int:product_id>/', UpdateProductPostView.as_view(), name='update_product_post'),



    # path('update-product-admin/<int:product_id>/', views.update_product_post, name='update_product_post'),
    # path('get-product-detail/<int:product_id>/', views.get_order_product_detail, name='get_product_detail'),

    

]

pop_up_cart/urls.py
from django.urls import path
from . import views

app_name = 'pop_up_cart'

urlpatterns = [
    path('', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update')
]

pop_up_email/urls.py
from django.urls import path
from . import views
from .views import (InviteFriendView)

app_name = 'pop_up_emails'
urlpatterns = [
    path('invite/',InviteFriendView.as_view(), name='invite'),
    path('auction-winner/', views.preview_email, name='auction_winner'),
    path('email-confirmation/', views.preview_email_confirmation, name='email_confirms'),
    path('two-factor-auth/', views.preview_two_factor_auth, name='two_factor_auth'),
    path('preview-order-confirmation/', views.preview_order_confirmation, name='preview_order_confirmation'),
    path('preview-shipping-details/', views.preview_send_customer_shipping_details, name='preview_shipping_details'),
    path('preview-invite-friend/', views.preview_invite_friend_email, name='invite_friend'),
    path('preview-interested-in-update/', views.preview_send_interested_in_and_coming_soon_product_update_to_users_email, name='interested_in_update')

]

pop_up_home/urls.py
from django.urls import path
from . import views
from django.contrib import sitemaps
from django.contrib.sitemaps.views import sitemap
from .sitemaps import StaticViewSitemap, ProductSitemap

app_name = 'pop_up_home'

sitemaps_dict = {
    "static": StaticViewSitemap,
    "products": ProductSitemap
}
urlpatterns = [
    path('', views.home_page, name='home'),
     # footer_links
    path('about/', views.about_us, name='about'),
    path('how-it-works/', views.how_it_works, name='how-it-works'),
    path('verification/', views.verification, name='verification'),
    path('contact/', views.contact_us, name='contact'),
    path('help-center/', views.help_center, name='help-center'),
    path('terms/', views.terms_and_conditions, name='terms'),
    path('privacy/', views.privacy_policy, name='privacy'),
    path('privacy-choices/', views.privacy_choice, name='privacy_choices'),
    path('site-map/', views.site_map, name='site-map'),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps_dict}, name="django.contrib.site.views.sitemap"),
    # help center pages
    path('buying-help/', views.buying_help, name='buying-help'),
    path('selling-help/', views.selling_help, name='selling-help'),
    path('account-help/', views.account_help, name='account-help'),
    path('shipping-help/', views.shipping_help, name='shipping-help'),
    path('payment-help/', views.payment_help, name='payment-help'),
    path('fees-help/', views.fees_help, name='fees-help'),
    path('friend-invite-success/', views.friend_invite_success, name='invite_success'),
    path('friend-invite-fail/', views.friend_invite_failure, name='invite_failed')

]

pop_up_payment/urls.py
from django.urls import path
# from pop_up_payment.views import stripe_webhook_view
from . import views
from .views import (ProductBuyView, ShippingAddressView, BillingAddressView, 
                    CreatePaymentIntentView,ProcessVenmoPaymentView, stripe_webhook_view)

app_name ='pop_up_payment'

urlpatterns = [
    path('webhooks/stripe/', views.stripe_webhook_view, name='stripe_webhook'),
    path('', ProductBuyView.as_view(), name='payment_home'),
    path('shipping-address/', ShippingAddressView.as_view(), name='shipping_address'),
    path('billing-address/', BillingAddressView.as_view(), name='billing_address'),
    path('placed-order/', views.placed_order, name='placed_order'),
    # path('error/', views.Error.as_view(), name='error'),
    path('create-payment-intent/', CreatePaymentIntentView.as_view(), name='create_payment'),
    path('braintree/get-client-token/', views.generate_client_token, name='get_client_token'),
    
    path('process-venmo/', ProcessVenmoPaymentView.as_view(), name='process_venmo'),
    # NowPayment
    path('create-nowpayments/', views.create_nowpayments_payment, name='create_nowpayments_payment'),
    path('finalize-nowpayments/', views.finalize_nowpayments_payment, name='finalize_nowpayments_payment'),
    path('check-nowpayments-status/<str:payment_id>/', views.check_nowpayments_status, name='check_nowpayments_status'),
    path('nowpayments-webhook/', views.nowpayments_webhook, name='nowpayments_webhook'),
    path('test-nowpayments/', views.test_nowpayments_connection, name='test_nowpayments_connection'),
    path('buy-now/<slug:slug>/', views.buy_now_add_to_cart, name='buy_now'),
]

pop_up_email/views.py
from django.shortcuts import render
from django.template.loader import render_to_string
from django.urls import reverse
from django.shortcuts import redirect
from django.utils.timezone import now
from datetime import timedelta, date, datetime
from django.http import HttpResponse
from pop_up_auction.models import PopUpProduct
from pop_up_email.utils import send_auction_winner_email, send_friend_invite_email
from django.views import View
from django.http import JsonResponse, HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin, AccessMixin, UserPassesTestMixin
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from django.contrib import messages

# Create your views here.


def preview_email(request):
    product = PopUpProduct.objects.first()
    user = request.user
    html = send_auction_winner_email(user, product)
    return HttpResponse(html)


def preview_email_confirmation(request):
    current_date = date.today()
    user = request.user
    user_email = request.user.email   
    year = current_date.strftime("%Y")
    context = {
        "user": user,
        "user_email": user_email,
        "year": year,
    }

    html = render_to_string('pop_up_email/email_confirm.html', context)
    return HttpResponse(html)

def preview_two_factor_auth(request):
    # 6 digit code
    six_digit_code = "123456"

    # user & user_email
    user  =request.user
    user_email = request.user.email

    # year
    current_date = date.today()
    year = current_date.strftime("%Y")

    # context
    context = {
        "user": user,
        "user_email": user_email,
        "code": six_digit_code,
        "year": year
    }

    # html
    html = render_to_string('pop_up_email/two_factor.html', context)

    # HttpResponse
    return HttpResponse(html)


def preview_order_confirmation(request):
    from pop_up_order.models import PopUpOrderItem, PopUpCustomerOrder
    user = request.user
    order = PopUpCustomerOrder.objects.filter(user=user).last()
    # items = PopUpOrderItem.objects.filter(order=order)
    items =[
        {"Product id": "53", "product_title": "Jordan 1 Retro High OG SP", 
         "secondary_product_title":"Union LA Chicago Shadow",
           "size":"9", "product_sex": "Male"},  {"Product id": "42", "product_title": "Jordan 11 Retro", 
         "secondary_product_title": "Gamma Blue",
           "size":"9", "product_sex": "Male"} ]

    print('items', items)

    order_id = "54f8f292-fd25-47dd-a7aa-a9a81b4a1c6a"
    total_paid =  "724.73"
    payment_status = "pending"
    html = render_to_string('pop_up_email/order_confirmation.html', {
        'user': user,
        'order_id': order.id,
        'items': items,
        'order_id': order_id,
        'total_paid':total_paid,
        'payment_status': payment_status
    })
   
    
    return HttpResponse(html)


def preview_send_customer_shipping_details(request):

    user = request.user
    user_email = request.user.email  

    order = "b62171e6-cb4b-48f6-be14-20d971393059"
    carrier = "UPS"
    tracking_no = "6547382910"
    shipped_at = datetime(2025, 7, 11)
    estimated_deliv = datetime(2025, 7, 15)
    status = 'Shipped'

    links_to_track_shipment = {
            "USPS": "https://tools.usps.com/go/TrackConfirmAction_input?_gl=1*ctcvbi*_ga*MjA2NDExMTY3Ni4xNzUxNTA0NzI3*_ga_QM3XHZ2B95*czE3NTI3MDA0MzkkbzExJGcxJHQxNzUyNzAwNTM0JGo2MCRsMCRoMA..",
            "UPS": "https://www.ups.com/us/en/home",
            "FedEx": "https://www.fedex.com/en-us/tracking.html"
    }

  
    html = render_to_string('pop_up_email/send_customer_shipping_details.html', {
        'user': user,
        'order_id': order_id,
        'carrier': carrier,
        'tracking_no': tracking_no,
        'shipped_at':shipped_at,
        'estimated_deliv': estimated_deliv,
        'status':status,
        'tracker_link': links_to_track_shipment[carrier]
    })

    return HttpResponse(html)


def preview_invite_friend_email(request):
    user = 'Peter'
    friend_name = 'Tom'
    html = render_to_string('pop_up_email/invite_friend.html', {
        'user': user,
        'friend_name': friend_name,
        'invite_link': "https://7c90b7218718.ngrok-free.app/?show_auth_modal=true"
    
    })
    return HttpResponse(html)

def preview_send_interested_in_and_coming_soon_product_update_to_users_email(request):
    product = PopUpProduct.objects.get(id=5)
    user = request.user
    product_id = 5
    buy_now_start_date = ""
    auction_start_date = datetime(2025, 8, 17, 18, 00)
    message_key = 'buy_now_update'
   

    html = render_to_string('pop_up_email/update_interested_users.html', {
       'user': user,
        'product': product, 
        'buy_now_start_date': buy_now_start_date if buy_now_start_date else "", 
        'auction_start_date': auction_start_date if auction_start_date else "", 
    
    })
    return HttpResponse(html)



class InviteFriendView(LoginRequiredMixin, View):

    def post(self, request):
        friend_name = request.POST.get('friend_name')
        friend_email = request.POST.get('friend_email')

        # verifiy good email address
        try:
            validate_email(friend_email)
        except ValidationError as e:
            return redirect(reverse('pop_up_home:invite_failed'))
        
        send_friend_invite_email(
            user=f"{request.user.first_name} {request.user.last_name}",
            user_email=request.user.email, 
            friend_name=friend_name, 
            friend_email=friend_email
            )

        messages.success(request, f'🎉  An invite has been sent to {friend_name}.  🎉')

        # Render success HTML page
        return redirect(reverse('pop_up_home:invite_success'))
        

pop_up_email/templates/pop_up_email/auction_winner.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Auction Winner</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Birthstone&display=swap');

        .logo-font {
            font-family: 'Birthstone', cursive;
            color: #CB3A60;
            font-size: 3.5rem;
            font-weight: 500;
        }

        /* Mobile Styles */
        @media only screen and (max-width: 600px) {
            .container {
                width: 100% !important;
                padding: 0 10px !important;
            }

            .stack {
                display: block !important;
                width: 100% !important;
            }

            .mobile-center {
                text-align: center !important;
            }

        }
    </style>
</head>

<body style="margin: 0; padding: 0; background-color: #f4f4f4; font-family: Arial, sans-serif;">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" bgcolor="#f4f4f4">
        <tr>
            <td align="center" style="padding: 20px">
                <table class="container" role="presentation" width="600" cellpadding="0" cellspacing="0" border="0"
                    bgcolor="#ffffff" style="border-radius: 0px; overflow: hidden; width: 600px; max-width: 600px">
                    <!--Header-->
                    <tr border="0" width="600" style="width: 600px; max-width: 600px">
                        <td align="center" width="600" style="background-color: #000; padding:20px;">
                            <div class="image-text">
                                <span class="image">
                                    <div class="logo-font"
                                        style="font-family: 'Birthstone', cursive, sans-serif; font-size: 3.5rem; color: #CB3A60;">
                                        The Pop Up
                                    </div>
                                </span>
                            </div>
                        </td>
                    </tr>
                    <!-- Message -->
                    <tr>
                        <td style="padding: 30px">
                            <h2 style="color: #CB3A60">🎉 Congratulations, {{ user.first_name }}</h2>
                            <p style="color: #CB3A60;">You've won the auction for the <strong>
                                    {{ product.product_title }} {{ product.secondary_product_title }}</strong>!</p>
                            <p style="color: #CB3A60">You have until
                                <strong>{{ deadlines|date:"F j, Y, g:i A" }}</strong>
                                to complete your purchase.
                            </p>
                            <!-- Product section -->
                            <table role="presentation" width="100%" cellpadding="10" cellspacing="0">
                                <tr>
                                    <td width="120">
                                        {% for image in product.product_image.all %}
                                        {% if image.is_feature %}
                                        <img src="{{ image.image }}" alt="{{ image.alt_text|default:'Product Image' }}"
                                            width="100" style="border-radius: 4px;">
                                        {% endif %}
                                        {% endfor %}
                                    </td>
                                    <td>
                                        <p style="margin: 0; color: #CB3A60;"><strong>{{ product.product_title}}
                                                {{ product.secondary_product_title }}</strong>
                                        </p>
                                        <p style="margin: 0; color: #CB3A60;">Winning Bid:
                                            ${{ product.current_highest_bid }}</p>
                                    </td>
                                </tr>
                            </table>
                            <!-- Button -->
                            <div style="text-align: center; margin-top: 30px;">
                                <a href="{% url 'pop_up_payment:payment_home' %}"
                                    style="background-color: #000; color: #CB3A60; padding: 12px 24px; text-decoration: none; border-radius: 4px; font-weight: bold;">
                                    Complete Purchase
                                </a>
                            </div>
                        </td>
                    </tr>
                    <!-- Footer -->
                    <tr>
                        <td align="center"
                            style="background-color: #f9f9f9; padding: 20px; font-size: 12px; color: #999;">
                            You're receiving this email because you participated in an auction at <a
                                href="https://thepopup.com" style="color: #999">The Pop Up</a>.<br>
                            If you didn't win this time, check thepopup.com for more auctions.
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</body>

</html>

pop_up_email/templates/pop_up_email/email_confirm.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Email Confirmation</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Birthstone&display=swap');

        .logo-font {
            font-family: 'Birthstone', cursive;
            color: #CB3A60;
            font-size: 3.5rem;
            font-weight: 500;
        }

        /* Mobile Styles */
        @media only screen and (max-width: 600px) {
            .container {
                width: 100% !important;
                padding: 0 10px !important;
            }

            .stack {
                display: block !important;
                width: 100% !important;
            }

            .mobile-center {
                text-align: center !important;
            }

        }
    </style>
</head>

<body style="margin: 0; padding: 0; background-color: #f4f4f4; font-family: Arial, sans-serif;">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" bgcolor="#f4f4f4">
        <tr>
            <td align="center" style="padding: 100px">
                <table role="presentation" class="container" width="600" cellpadding="0" cellspacing="0" border="0"
                    bgcolor="#ffffff" style="border-radius: 0px; overflow: hidden; width: 600px; max-width: 600px">
                    <tr border="0" width="600" style="width: 600px; max-width: 600px">
                        <td align="left" width="600" style="background-color: #000; padding:20px;">
                            <div class="image-text">
                                <span class="image">
                                    <div class="logo-font"
                                        style="font-family: 'Birthstone', cursive, sans-serif; font-size: 3.5rem; color: #CB3A60;">
                                        The Pop Up
                                    </div>
                                </span>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td style="padding: 30px">
                            <h2 style="color: #CB3A60; font-size: 32px;">Welcome {{ user.first_name }}!</h2>
                            <p style="color: #CB3A60; font-size: 20px;">Thanks for joining us! Please confirm your email
                                to continue.</p>

                            <!-- Button -->
                            <div style="text-align: left; margin-top: 30px;">
                                <a href="{% url 'pop_up_payment:payment_home' %}"
                                    style="background-color: #000; color: #CB3A60; padding: 12px 24px; text-decoration: none; border-radius: 4px; font-weight: bold;">
                                    Confirm Email
                                </a>
                            </div>
                        </td>
                    </tr>
                    <!-- Footer -->
                    <tr>
                        <td align="left"
                            style="background-color: #f9f9f9; padding: 20px; font-size: 12px; color: #999; font-size: 12px">
                            &copy {{ year }} The Pop Up
                        </td>
                    </tr>
                </table>

            </td>
        </tr>
    </table>
</body>

</html>

pop_up_email/templates/pop_up_email/one_hour_reminder.html
<body>
    <h1>Hey! You've got an hour to pay for the product you won in The Pop Up auction.</h1>
</body>

pop_up_email/templates/pop_up_email/send_customer_shipping_details.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Order Confirmation</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Birthstone&display=swap');

        .logo-font {
            font-family: 'Birthstone', cursive;
            color: #CB3A60;
            font-size: 3.5rem;
            font-weight: 500;
        }

        /* Mobile Styles */
        @media only screen and (max-width: 600px) {
            .container {
                width: 100% !important;
                padding: 0 10px !important;
            }

            .stack {
                display: block !important;
                width: 100% !important;
            }

            .mobile-center {
                text-align: center !important;
            }

        }
    </style>
</head>

<body style="margin: 0; padding: 0; background-color: #f4f4f4; font-family: Arial, sans-serif;">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" bgcolor="#f4f4f4">
        <tr>
            <td align="center" style="padding: 20px">
                <table class="container" role="presentation" width="700" cellpadding="0" cellspacing="0" border="0"
                    bgcolor="#ffffff" style="border-radius: 0px; overflow: hidden; width: 700px; max-width: 700px">
                    <!--Header-->
                    <tr border="0" width="600" style="width: 600px; max-width: 600px">
                        <td align="center" width="600" style="background-color: #000; padding:20px;">
                            <div class="image-text">
                                <span class="image">
                                    <div class="logo-font"
                                        style="font-family: 'Birthstone', cursive, sans-serif; font-size: 3.5rem; color: #CB3A60;">
                                        The Pop Up
                                    </div>
                                </span>
                            </div>
                        </td>
                    </tr>
                    <!-- Message -->
                    <tr>
                        <td style="padding: 20px 30px 0 30px;">
                            <h4 style="color: #CB3A60">Hello {{ user.first_name }},</h4>
                            <p style="color: #CB3A60">Your order, order #<a
                                    href="{% url 'pop_accounts:customer_order' order %}">{{ order }}</a>,
                                has shipped.
                            </p>
                            <p style="color: #CB3A60"><strong>Status:</strong> <span>{{ status }}</span></p>
                            <p style="color: #CB3A60"><strong>Shipping Date:</strong>
                                <span>{{ shipped_at|date:"F j, Y" }}</span>
                            </p>
                            <p style="color: #CB3A60"><strong>Estimated Delivery Date:</strong> <span>
                                    {{ estimated_deliv|date:"F j, Y" }}</span></p>
                            <p style="color: #CB3A60"><strong>Carrier:</strong> <span>{{ carrier }}</span></p>
                            <p style="color: #CB3A60"><strong>Tracking No.:</strong> <span>
                                    <a href="{{ tracker_link }}">{{ tracking_no }}</a></span>
                            </p>
                        </td>
                    </tr>
                    <tr>
                        <td align="center" style="padding: 12px 30px 24px 30px;">
                            <hr style="border: 0; height: 1px; background: #ddd;">
                            <h2 style="color: #CB3A60; margin: 16px 0 0 0">Enjoy your purchase!</h2>
                        </td>
                    </tr>
                    <!-- Footer -->
                    <tr>
                        <td align="center"
                            style="margin: 0; background-color: #f9f9f9; padding: 30px; font-size: 12px; color: #999;">
                            You're receiving this email because you made a purchase at <a href="https://thepopup.com"
                                style="color: #999">The Pop Up</a>.<br>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</body>

</html>

pop_up_email/templates/pop_up_email/twenty_four_hour_reminder.html
<body>
    <h1>Hey! You've got 24 hours to pay for the product you won in The Pop Up auction.</h1>
</body>