pop_accounts/urls.py
from django.urls import path
from . import views
from .views import (EmailCheckView, RegisterView, Login2FAView, VerifyEmailView, PastPurchaseView,
                    UserLogOutView, UserDashboardView, Verify2FACodeView, AccountDeletedView,
                    UserInterestedInView, MarkProductInterestedView, MarkProductOnNoticeView, 
                    UserOnNoticeView, OpenBidsView, AdminInventoryView, EnRouteView, AddProductsView,
                    UpdateProductView, CompleteProfileView, PersonalInfoView, GetAddressView, PastBidView,
                    DeleteAddressView, SetDefaultAddressView, DeleteAccountView, UserPasswordResetConfirmView,
                    ShippingTrackingView, UserOrderPager, AdminDashboardView, SalesView, MostOnNotice, 
                    MostInterested, TotalOpenBidsView, TotalAccountsView, AccountSizesView, 
                    PendingOkayToShipView, PendingOrderShippingDetailView, UpdateShippingView, 
                    GetOrderShippingDetail, UpdateShippingPostView, ViewShipmentsView, AddProductsGetView,
                    Resend2FACodeView, SendPasswordResetLink, SocialLoginCompleteView)

app_name = 'pop_accounts'
urlpatterns = [

    # Auth register / login class based views
    path('auth/check-email/', EmailCheckView.as_view(), name='check_email'),
    path('auth/register/', RegisterView.as_view(), name='register'),
    path('verify/<uidb64>/<token>/', VerifyEmailView.as_view(), name='verify_email'),
    path('auth/user-login/', Login2FAView.as_view(), name='user_login'),

    # Social Auth / Social Login
    path('auth/complete-profile/', CompleteProfileView.as_view(), name='complete_profile'),
    path('social-login-complete/', SocialLoginCompleteView.as_view(), name='social_login_complete'),
    path('get-user-info/', views.get_user_info, name="get_user_info"),

    
    # Auth register / login
    path('auth/verify-code/', Verify2FACodeView.as_view(), name='verify_2fa'),
    path('auth/send-reset-link/', SendPasswordResetLink.as_view(), name='send_reset_link'),
    path('resend-code/', Resend2FACodeView.as_view(), name='resend_2fa_code'),
    path('password-reset/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('logout/',UserLogOutView.as_view(), name='logout'),
       
    # path('place-bid/', DashboardPlaceBidView.as_view(), name='place_bid'),

    # User Info
    path('dashboard/', UserDashboardView.as_view(), name='dashboard'),
    path('personal-information/', views.PersonalInfoView.as_view(), name='personal_info'),
    path('delete-account/', DeleteAccountView.as_view(), name='delete_account'),
    path('account-deleted/', AccountDeletedView.as_view(), name='account_deleted'),    
    path('get-address/<uuid:address_id>/', GetAddressView.as_view(), name='get_address'),
    path('delete-address/<uuid:address_id>/', DeleteAddressView.as_view(), name='delete_address'),
    path('set-default-address/<uuid:address_id>/', SetDefaultAddressView.as_view(), name='set_default_address'),
    path('interested-in/', UserInterestedInView.as_view(), name='interested_in'),
    path('mark-interested/', MarkProductInterestedView.as_view(), name='mark_interested'),
    path('on-notice/', UserOnNoticeView.as_view(), name='on_notice'),
    path('mark-on-notice/', MarkProductOnNoticeView.as_view(), name='mark_on_notice'),
    path('open-bids/', OpenBidsView.as_view(), name="open_bids"),
    path('bids-history/', PastBidView.as_view(), name='past_bids'),
    path('purchase-history/', PastPurchaseView.as_view(), name='past_purchases'),
    path('shipping-tracking/', ShippingTrackingView.as_view(), name='shipping_tracking'),
    path('customer-order/<uuid:order_id>/', UserOrderPager.as_view(), name='customer_order'),

    # admin dashboard
    path('dashboard-admin/', AdminDashboardView.as_view(), name='dashboard_admin'),
    path('inventory-admin/', AdminInventoryView.as_view(), name='inventory_admin'),
    path('inventory-admin/<slug:slug>/', AdminInventoryView.as_view(), name='inventory_admin'),
    path('sales-admin/', SalesView.as_view(), name='sales_admin'),
    path('most-on-notice-admin/', MostOnNotice.as_view(), name='most_on_notice'),
    path('most-interested-admin/', MostInterested.as_view(), name='most_interested'),
    path('total-open-bids-admin/', TotalOpenBidsView.as_view(), name='total_open_bids'),
    path('total-accounts-admin/', TotalAccountsView.as_view(), name='total_accounts'),
    path('account-sizes-admin/', AccountSizesView.as_view(), name='account_sizes'),
    path('pending-okay-to-ship/', PendingOkayToShipView.as_view(), name='pending_okay_to_ship'),
    path('get-pending-order-shipping-detail/<uuid:order_no>/', PendingOrderShippingDetailView.as_view(), name='get_order_details'),

    path('update-shipping-admin/', UpdateShippingView.as_view(), name='update_shipping'),
    path('update-shipping-admin/<int:shipment_id>/', UpdateShippingPostView.as_view(), name='update_shipping_post'),
    path('get-shipping-detail/<int:shipment_id>/', GetOrderShippingDetail.as_view(), name='get_shipping_detail'),

    path('shipments-admin/', ViewShipmentsView.as_view(), name='shipments'),
    path('dashboard-en-route/', EnRouteView.as_view(), name='enroute'),
    path('dashboard-en-route/<slug:slug>/', EnRouteView.as_view(), name='enroute'),

    # admin dashboard | Adding products
    path('add-products-admin/', AddProductsView.as_view(), name='add_products'),
    path('add-products-admin/<int:product_type_id>/', AddProductsGetView.as_view(), name='add_products_get'),

    # admin dashboard | Updating products
    path('update-product-admin/', UpdateProductView.as_view(), name='update_product'),
    path('update-product-admin/<int:product_id>/', UpdateProductView.as_view(), name='update_product_detail'),
    # path('get-product-detail/<int:product_id>/<int:product_type_id>/', ProductDetailView.as_view(), name='get_product_detail'),
    # path('update-product-post/<int:product_id>/', UpdateProductPostView.as_view(), name='update_product_post'),



    # path('update-product-admin/<int:product_id>/', views.update_product_post, name='update_product_post'),
    # path('get-product-detail/<int:product_id>/', views.get_order_product_detail, name='get_product_detail'),

    

]

pop_up_auction/urls.py
from django.urls import path
from . import views
from .views import (PlaceBidView, AllAuctionView, ProductAuctionView, ProductsView, 
                    ComingSoonView, FutureReleases, ProductDetailView)

app_name = 'pop_up_auction'
urlpatterns = [
    path('', AllAuctionView.as_view(), name="auction"),
    path('place-bid/', PlaceBidView.as_view(), name='place_bid'),
    path('open/', ProductAuctionView.as_view(), name='product_auction'),
    path('open/<slug:slug>/', ProductAuctionView.as_view(), name='product_auction'),
    # path('product-buy/', ProductBuyView.as_view(), name='product_buy'),
    path('products/', ProductsView.as_view(), name='products'),
    path('products/<slug:slug>/', ProductsView.as_view(), name='products'),
    path('coming-soon/', ComingSoonView.as_view(), name='coming_soon'),
    path('coming-soon/<slug:slug>/', ComingSoonView.as_view(), name='coming_soon'),
    path('future-releases/', FutureReleases.as_view(), name='future_releases'),
    path('future-releases/<slug:slug>/', FutureReleases.as_view(), name='future_releases'),
    path('<slug:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('past-product-details/<int:item_id>/', views.past_product_detail, name='past_product_details'),
    path('past-bids-product-detail/<int:product_id>/', views.past_bid_product_detail_by_product, name='past_bids_product_detail')
   
]

pop_up_cart/urls.py
from django.urls import path
from . import views

app_name = 'pop_up_cart'

urlpatterns = [
    path('', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update')
]

pop_up_payment/urls.py
from django.urls import path
# from pop_up_payment.views import stripe_webhook_view
from . import views
from .views import (ProductBuyView, ShippingAddressView, BillingAddressView, 
                    CreatePaymentIntentView,ProcessVenmoPaymentView, stripe_webhook_view)

app_name ='pop_up_payment'

urlpatterns = [
    path('webhooks/stripe/', views.stripe_webhook_view, name='stripe_webhook'),
    path('', ProductBuyView.as_view(), name='payment_home'),
    path('shipping-address/', ShippingAddressView.as_view(), name='shipping_address'),
    path('billing-address/', BillingAddressView.as_view(), name='billing_address'),
    path('placed-order/', views.placed_order, name='placed_order'),
    # path('error/', views.Error.as_view(), name='error'),
    path('create-payment-intent/', CreatePaymentIntentView.as_view(), name='create_payment'),
    path('braintree/get-client-token/', views.generate_client_token, name='get_client_token'),
    
    path('process-venmo/', ProcessVenmoPaymentView.as_view(), name='process_venmo'),
    # NowPayment
    path('create-nowpayments/', views.create_nowpayments_payment, name='create_nowpayments_payment'),
    path('finalize-nowpayments/', views.finalize_nowpayments_payment, name='finalize_nowpayments_payment'),
    path('check-nowpayments-status/<str:payment_id>/', views.check_nowpayments_status, name='check_nowpayments_status'),
    path('nowpayments-webhook/', views.nowpayments_webhook, name='nowpayments_webhook'),
    path('test-nowpayments/', views.test_nowpayments_connection, name='test_nowpayments_connection'),
    path('buy-now/<slug:slug>/', views.buy_now_add_to_cart, name='buy_now'),
]

pop_up_auction/templates/auction/auction.html
{% extends "layout.html" %}
{% load static %}
{% load custom_math %}
{% load email_filters %}
{% load humanize %}

{% block title %}
Auction
{% endblock %}

{% block main %}

<div class="section_container">
    <div class="page_title">
        <h2>Current Auction</h2>
    </div>
    <div class="the_auction_container">
        {% for i in in_auction %}
        <div class="item_container_two product_display_container_long">
            <a href="{% url 'pop_up_auction:product_auction' i.slug %}" class="auction_product_detail_container">
                <div class="auct_prod_title_container_two">
                    <h3>{{ i.product_title }}</h3>
                    <h3>{{ i.secondary_product_title }}</h3>
                </div>
                <div class="auct_img_container">
                    {% for image in i.product_image.all %}
                    {% if image.is_feature %}
                    <img class="min_img_fluid"
                        src="{% if image.get_image_url  %} {{ image.get_image_url  }} {% else %} {{ image.image }}{% endif %}"
                        alt="{{ image.alt_text }}">
                    {% endif %}
                    {% endfor %}
                </div>
                <div class="sub_auction_product_detail_container">

                    <h4>Size</h4>
                    {% if product_specifications.product_sex == "Male" %}
                    <h4>U.S. {{"Mens"}} {{product_specifications.size }}</h4>
                    {% else %}
                    <h4>U.S. {{"Womens"}} {{product_specifications.size }}</h4>
                    {% endif %}
                </div>
                <div class="sub_auction_product_detail_container">
                    <h4>Condition</h4>
                    <h4>{{product_specifications.condition|capfirst }}</h4>
                </div>
            </a>
            <div class="auction_prod_links_container">
                <div class="highest_bid_container">
                    {% if i.current_highest_bid %}
                    <h4>Highest Bid</h4>
                    <h2 class="current_bid_display" data-product-id="{{ i.id }}">
                        ${{i.current_highest_bid|intcomma}}
                    </h2>
                    {% else %}
                    <h3>Awaiting the first bid</h3>
                    {% endif %}
                </div>
                {% if user.is_authenticated %}
                <button class="button_long bidButtonClass" data-product-id="{{ i.id }}">Make Bid</button>
                {% else %}
                <button class="button_long loginPrompt">Sign in to Bid</button>
                {% endif %}
            </div>
            <div class="auction_product_auction_details">
                {% if i.auction_duration %}
                <h4>Auction closes in</h4>
                <h2>{{ i.auction_duration.days}}</h2>
                {% if i.auction_duration.days > 1 %}
                <h3>Days</h3>
                {% else %}
                <h3>Day</h3>
                {% endif %}
                <div class="auction_product_auction_details_hours">
                    <h2>{{ i.auction_duration.hours}} <span>Hours</span></h2>
                </div>
                {% else %}
                <h4>Auction Hasn't Started Yet</h4>
                {% endif %}
            </div>
        </div>
        {% comment %}
        <!-- Bid Modal -->
        {% endcomment %}
        <div class="modal fade" id="bidModal-{{i.id}}" tabindex="-1" aria-labelledby="bidModalLabel" aria-hidden="true">
            <div class="modal_content">

                <div class="modal_header">
                    <h3 class="modal-title" id="bidModalLabel">Place Your Bid</h3>
                    <button type="button" class="btn-close closeModal" aria-label="Close">X</button>
                </div>
                <div class="modal_bid_shipping_days_left">
                    <div class="modal_bid_and_shipping">
                        {% if i.current_highest_bid %}
                        <h5>${{i.current_highest_bid|compute_number:10|intcomma}}.00</h5>
                        {% else %}
                        <h5>Bid price</h5>
                        {% endif %}
                        <h5> + Shipping</h5>
                    </div>
                    <div class="modal_bid_numb_of_bids">
                        <h5 class="current_bid_count"><span class="current_bid_count_value"
                                data-product-id="{{ i.id }}">{{ i.bid_count}}</span>bids
                        </h5>
                    </div>
                    <div class="modal_bid_days_left">
                        <h5><span>{{ i.auction_duration.days}}</span>days left</h5>
                    </div>
                </div>
                <div class="modal_body">
                    <form class="bidForm" id="bidForm-{{ i.id }}" method="POST"
                        action="{% url 'pop_up_auction:place_bid' %}" data-product-id="{{ i.id }}">
                        {% csrf_token %}
                        <div id="predefined_bids-{{ i.id }}" class="predefined_bids" data-product-id="{{ i.id }}">
                            {% if i.current_highest_bid %}
                            {% for inc in quick_bid_increments %}
                            {% with new_bid=i.current_highest_bid|compute_number:inc %}
                            <button type="button" data-amount="{{ new_bid }}" class="button_long_small quick_bid">Bid
                                <span>
                                    ${{new_bid|intcomma }}.00</span></button>
                            {% endwith %}
                            {% endfor %}
                            {% endif %}

                        </div>

                        <div class="bid_modal_input_container">
                            <input type="hidden" name="product_id" value="{{ i.id }}">
                            <label for="custom_bid">
                                <span>or enter your bid</span>
                            </label>
                            <div class="modal_bid_input_submit_btn">
                                <div class="outer_input_container">
                                    <h4>$</h4>

                                    <input type="number" step="0.01" id="custom_bid-{{ i.id }}" name="bid_amount"
                                        class="form-control" required
                                        min="{{i.current_highest_bid|compute_number:1|intcomma}}.00"
                                        placeholder="Enter custom bid">
                                </div>
                                <div class="mt-3">
                                    <button type="submit" class="btn button_long_small" id="submitBid-{{ i.id }}">Submit
                                        Bid</button>
                                </div>
                            </div>
                            {% if i.current_highest_bid %}
                            <p class="bid_hint">Enter
                                <span>${{i.current_highest_bid|compute_number:1|intcomma}}.00</span> or more
                            </p>
                            {% else %}
                            <p class="bid_hint">Enter <span>${{i.reserve_price|compute_number:1|intcomma}}.00</span>
                                or more</p>
                            {% endif %}
                        </div>
                    </form>
                    <div class="bid_response" style="color:red"></div>
                </div>
                <div class="modal_user_abbr_user_info">
                    <div class="modal_user_pay_email_shipping_container">
                        {% for image in i.product_image.all %}
                        {% if image.is_feature %}
                        <img class="modal_user_card_img"
                            src="{% if image.get_image_url  %} {{ image.get_image_url  }} {% else %} {{ image.image }}{% endif %}"
                            alt="{{ image.alt_text}}">
                        {% endif %}
                        {% endfor %}
                        {% if user.is_authenticated %}
                        <p>{{ user.email|obfuscate_email }}</p>
                        {% endif %}
                        <p>ship to <span>{{ user_zip }}</span></p>
                    </div>
                    <div class="modal_user_info_update_container">
                        <a href="{% url 'pop_accounts:personal_info' %}">Update</a>
                    </div>
                </div>
                <div class="modal_purchase_disclaimer">
                    <p>
                        By selecting to submit bid, you authorize The Pop Up to bid up to your max bid and if
                        you win, charge your bid amount and related costs to your <span>PayPal</span> account.
                        You also agree to The Pop Up's User Agreement and Privacy Notice.
                    </p>
                </div>
            </div>
        </div>
        <!-- End of Bid Modal -->
        {% endfor %}
    </div>
</div>
{% endblock %}
<scrip src="{% static 'js/payment.js' %}">
    $(document).on('click', '.buy-now-button', function (e) {
    e.preventDefault();
    $.ajax({
    type: 'POST',
    url: '{% url "pop_up_cart:cart_add" %}',
    data: {
    productid: $('.buy-now-button').val(),
    <!-- productqty: $('#select option:selected').text(), -->
    csrfmiddlewaretoken: "{{csrf_token}}",
    action: 'post'
    },
    success: function (json) {
    document.getElementById("basket-qty").innerHTML = json.qty
    },
    error: function (xhr, errmsg, err) {}
    });
    })
</scrip>

pop_up_auction/templates/auction/coming_soon.html
{% extends "layout.html" %}
{% load static %}


{% block title %}
Auction
{% endblock %}

{% block main %}

<div class="section_container">
    <div class="page_title">
        <h2>Coming Soon</h2>
    </div>
    <div class="product_type_container">
        <div class="product_type_item_select">
            <ul>
                <li {% if not product_type %} class="selected" {% endif %}>
                    <a href="{% url 'pop_up_auction:coming_soon' %}">All</a>
                </li>

                {% for c in product_types %}
                {% if product_type and product_type.slug == c.slug %}
                <li class="selected">
                    {% else %}
                <li>
                    {% endif %}
                    <a href="{% url 'pop_up_auction:coming_soon' c.slug %}">{{ c.name|capfirst }}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="cs_container">
        {% if product %}
        {% for prod in product %}
        <div class="cs_display_container">
            <div class="rectangle_image_container">
                <div class="background_rectangle"></div>
                {% for image in prod.product_image.all %}
                {% if image.is_feature %}
                <img class="img_fluid_cs" alt="{{ image.alt_text }}" src="{{ image.get_image_url }}" />
                {% endif %}
                {% endfor %}
            </div>

            <div class="cs_desc_container">
                <h3>{{ prod.specs.model_year }}</h3>
                <h3>{{ prod.product_title }}</h3>
                <h3>{{ prod.secondary_product_title}}</h3>
            </div>
            <div class="cs_button_container">
                {% if user.is_authenticated and prod in user.prods_on_notice_for.all %}
                <button class="button_medium notify-me-button" data-product-id="{{ prod.id }}" data-interested="true">On
                    Notice ❤️</button>
                {% else %}
                <button class="button_medium notify-me-button" data-product-id="{{ prod.id }}"
                    data-interested="false">Notify
                    Me
                </button>
                {% endif %}
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h4>Nothing to display</h4>
        {% endif %}
    </div>
</div>

{% endblock %}

pop_up_auction/templates/auction/future_releases.html
{% extends "layout.html" %}
{% load static %}


{% block title %}
Auction
{% endblock %}

{% block main %}

<div class="section_container">
    <div class="page_title">
        <h2>Future Releases</h2>
    </div>
    <div class="product_type_container">
        <div class="product_type_item_select">
            <ul>
                <li {% if not product_type %} class="selected" {% endif %}>
                    <a href="{% url 'pop_up_auction:future_releases' %}">All</a>
                </li>

                {% for c in product_types %}
                {% if product_type and product_type.slug == c.slug %}
                <li class="selected">
                    {% else %}
                <li>
                    {% endif %}
                    <a href="{% url 'pop_up_auction:future_releases' c.slug %}">{{ c.name|capfirst }}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="fr_container">
        {% if product %}
        {% for prod in product %}
        <div class="fr_display_container">
            <div class="triangle_image_container">
                <div class="background_triangle"></div>
                {% for image in prod.product_image.all %}
                {% if image.is_feature %}
                <img class="img_fluid_fr" alt="{{ image.alt_text }}"
                    src="{% if image.get_image_url  %} {{ image.get_image_url  }} {% else %} {{ image.image }}{% endif %}" />
                {% endif %}
                {% endfor %}

            </div>

            <div class="fr_desc_container">
                <h3>{{ prod.specs.model_year }}</h3>
                <h3>{{ prod.product_title }}</h3>
                <h3>{{ prod.secondary_product_title}}</h3>
            </div>
            <div class="fr_button_container">
                {% if user.is_authenticated and prod in user.prods_interested_in.all %}
                <button class="button_medium interested_btn" data-product-id="{{ prod.id }}"
                    data-interested="true">Interested ❤️</button>
                {% else %}
                <button class="button_medium interested_btn" data-product-id="{{ prod.id }}"
                    data-interested="false">Interested</button>
                {% endif %}
            </div>
        </div>

        {% endfor %}
        {% else %}
        <h4>Nothing to display</h4>
        {% endif %}
    </div>
</div>

{% endblock %}

pop_up_auction/templates/auction/past_bid_detail.html
{% extends "layout.html" %}
{% load static %}
{% load humanize %}


{% block title %}
Past Product Detail
{% endblock %}

{% block main %}

<div class="section_container">
    <div class="page_title">
        <h2>{{ product.product_title }}</h2>
        <h3>{{ product.secondary_product_title }}</h3>
        <h4>{{ product_specifications.model_year }}</h4>
    </div>
    <div class="product_details_container">
        <div class="product_details_container_left">
            <div class="pd_circle_image_container">
                <div class="pd_background_circle"></div>


                {% for image in product.product_image.all %}
                {% if image.is_feature %}
                <img class="img_fluid_product_details" alt="{{ image.alt_text }}" src="{{ image.get_image_url }}"
                    alt="{{ image.image.alt_text}}" />
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="lower_auction_container">
        <div class="prod_auct_desc_container">
            <h3>Product Description</h3>
            <p>
                {{ product.description }}
            </p>
        </div>

        <div class="prod_auct_details_container">

            <div class="auct_details_style_container">

                <h4 class="prod_auct_details_title">Style</h4>
                <p>{{ product.specs.style_number }}</p>
            </div>
            <div class="auct_details_colorway_container">
                <h4 class="prod_auct_details_title">Colorway</h4>
                <p>{{ product.specs.colorway }}</p>
            </div>
            <div class="auct_details_release_container">

                <h4 class="prod_auct_details_title">Release Date</h4>
                <p>{{ product.specs.release_date }}</p>
            </div>
            <div class="auct_details_retail_container">
                <h4 class="prod_auct_details_title">Retail</h4>
                <p>${{ product.retail_price }}</p>
            </div>

        </div>

        <div class="verified_return_container">
            <div class="databox_medium_dark">
                <div class="databox_medium_dark_title_box">
                    <i class='bx bx-award'></i>
                    <h3>100% Guaranteed Authentic</h3>
                </div>
                <p>
                    Always real. Really really real! If we don't use resellers. We buy it from the manufacturer and
                    resell.
                </p>
                <a href="/">Learn More</a>
            </div>
            <div class="databox_medium_dark">
                <div class="databox_medium_dark_title_box">
                    <i class="fa-solid fa-arrow-rotate-left"></i>
                    <h3>Return Policy</h3>
                </div>
                <p>
                    Learn more about our return policy by clicking on the link below.
                </p>
                <a href="/">Learn More</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

pop_up_auction/templates/auction/products.html
{% extends "layout.html" %}
{% load static %}


{% block title %}
Products
{% endblock %}

{% block main %}

<div class="section_container">
    <div class="page_title">
        <h2>Products</h2>
    </div>
    <div class="product_type_container">
        <div class="product_type_item_select">
            <ul>
                <li {% if not product_type %} class="selected" {% endif %}>
                    <a href="{% url 'pop_up_auction:products' %}">All</a>
                </li>

                {% for c in product_types %}
                {% if product_type and product_type.slug == c.slug %}
                <li class="selected">
                    {% else %}
                <li>
                    {% endif %}
                    <a href="{% url 'pop_up_auction:products' c.slug %}">{{ c.name|capfirst }}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="products_container">
        {% if product %}
        {% for p in product %}
        <div class="product_display_container">

            <a href="{{ p.get_absolute_url }}">
                <div class="circle_image_container">
                    <div class="background_circle"></div>
                    {% for image in p.product_image.all %}
                    {% if image.is_feature %}
                    {% if p.product_type.slug == "shoe" %}
                    <img class="img_fluid_product" alt="{{ image.alt_text }}" src="{{ image.get_image_url }}" />
                    {% else %}
                    <img class="img_fluid_product_non_shoe" alt="{{ image.alt_text }}"
                        src="{{ image.get_image_url }}" />
                    {% endif %}
                    {% endif %}
                    {% endfor %}
                </div>
            </a>


            <div class="products_desc_container">
                {% if p.specs.model_year %}
                <h3>{{ p.specs.model_year }}</h3>
                {% endif %}
                <h3>{{ p.product_title }}</h3>
                <h3>{{ p.secondary_product_title }}</h3>
            </div>
            <div class="products_button_container">
                {% if request.user.is_authenticated %}
                <a class="button_medium" href="{% url 'pop_up_payment:buy_now' p.slug %}">Buy Now</a>
                {% else %}
                <button class="button_medium signUpModalBtn">Log In To Buy Now</button>
                {% endif %}
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h4 style="color: #CB3A60">Nothing to display</h4>
        {% endif %}
    </div>
</div>
<script>
    $(document).ready(function () {

        $('.add_to_cart_button').on('click', function (e) {
            e.preventDefault();

            let productId = $(this).data('product-id');
            let productQty = 1;  // Default quantity to add. You can modify if you allow qty selection.

            $.ajax({
                type: 'POST',
                url: '{% url "pop_up_cart:cart_add" %}',
                data: {
                    productid: productId,
                    productqty: productQty,
                    action: 'POST',
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                },
                success: function (json) {
                    console.log('Cart Updated:', json.qty);
                    // Optional: update cart count in navbar, or show toast message
                    $('#cart_qty').fadeOut(150).text(json.qty).fadeIn(150)
                },
                error: function (xhr, errmsg, err) {
                    console.error("Cart add failed:", errmsg);
                }
            });
        });
    });
</script>
{% endblock %}