pop_up_cart/urls.py
from django.urls import path
from . import views

app_name = 'pop_up_cart'

urlpatterns = [
    path('', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update')
]

pop_up_payment/urls.py
from django.urls import path
# from pop_up_payment.views import stripe_webhook_view
from . import views
from .views import (ProductBuyView, ShippingAddressView, BillingAddressView, 
                    CreatePaymentIntentView,ProcessVenmoPaymentView, stripe_webhook_view)

app_name ='pop_up_payment'

urlpatterns = [
    path('webhooks/stripe/', views.stripe_webhook_view, name='stripe_webhook'),
    path('', ProductBuyView.as_view(), name='payment_home'),
    path('shipping-address/', ShippingAddressView.as_view(), name='shipping_address'),
    path('billing-address/', BillingAddressView.as_view(), name='billing_address'),
    path('placed-order/', views.placed_order, name='placed_order'),
    # path('error/', views.Error.as_view(), name='error'),
    path('create-payment-intent/', CreatePaymentIntentView.as_view(), name='create_payment'),
    path('braintree/get-client-token/', views.generate_client_token, name='get_client_token'),
    
    path('process-venmo/', ProcessVenmoPaymentView.as_view(), name='process_venmo'),
    # NowPayment
    path('create-nowpayments/', views.create_nowpayments_payment, name='create_nowpayments_payment'),
    path('finalize-nowpayments/', views.finalize_nowpayments_payment, name='finalize_nowpayments_payment'),
    path('check-nowpayments-status/<str:payment_id>/', views.check_nowpayments_status, name='check_nowpayments_status'),
    path('nowpayments-webhook/', views.nowpayments_webhook, name='nowpayments_webhook'),
    path('test-nowpayments/', views.test_nowpayments_connection, name='test_nowpayments_connection'),
    path('buy-now/<slug:slug>/', views.buy_now_add_to_cart, name='buy_now'),
]

templates/payment/billing_address.html
{% extends "layout.html" %}
{% load static %}
{% load humanize %}

{% block title %}
Payment
{% endblock %}

{% block main %}
{% if user.is_authenticated %}
<div class="section_container">
    <div class="page_title">
        <h2>Billing Address</h2>
    </div>
    <div class="billing_address_container">
        <!-- Button Navigation -->
        <div class="billing_address_buttons">
            <button type="button" class="billing_address_button activated" data-tab="edit-tab">Edit
                Address</button>
            <button type="button" class="billing_address_button" data-tab="choose-tab">Choose
                Other</button>
            <button type="button" class="billing_address_button" data-tab="new-tab">Add
                new</button>
        </div>
        <!-- Edit Address Tab -->
        <form action="{% url 'pop_up_payment:billing_address' %}" method="post"
            class="billing_address_content activated" id="edit-tab">
            {% csrf_token %}

            <input type="hidden" name="address_id" value="{{ address_form.instance.id }}">

            <div class="ship_to_name_update_modal_container">
                <div class="billing_address_inputs">
                    {{ address_form.prefix }}
                </div>
                <div class="personal_info_names_container">
                    <div class="personal_info_add_medium">
                        {{ address_form.first_name }}
                    </div>
                    <div class="personal_info_add_medium">
                        {{ address_form.middle_name}}
                    </div>
                    <div class="personal_info_add_medium">
                        {{ address_form.last_name }}
                    </div>
                </div>
                <div class="billing_address_inputs">
                    {{ address_form.suffix }}
                </div>
            </div>
            <div class="ship_to_address_update_modal_container">
                <div class="personal_info_add_long">
                    {{ address_form.address_line }}
                </div>
                <div class="personal_info_add_long">
                    {{ address_form.address_line2 }}
                </div>
                <div class="personal_info_add_small">
                    {{ address_form.apartment_suite_number }}
                </div>
                <div class="personal_info_city_state_zip_container">
                    <div class="personal_info_add_medium">
                        {{ address_form.town_city }}
                    </div>
                    <div class="personal_info_choice_inputs">
                        {{ address_form.state}}
                    </div>
                    <div class="personal_info_add_small">
                        {{ address_form.postcode }}
                    </div>
                </div>

                <div class="billing_address_delivery_instructions">
                    {{ address_form.delivery_instructions }}
                </div>
            </div>
            <div class="default_billing_address_container">
                {{ edit_address_form.is_default_billing.label }}
                {{ edit_address_form.is_default_billing }}
            </div>
            <input class="button_medium" type="submit" value="Save"></input>
        </form>

        <div class="billing_add_address_tab billing_address_content" id="choose-tab">
            <p>Select from Your Saved Addresses:</p>
            <form action="{% url 'pop_up_payment:billing_address' %}" class="select_address_form" method="POST">
                {% csrf_token %}
                {% for addy in saved_addresses %}
                <label>
                    <input type="radio" name="selected_address" value="{{ addy.id }}">
                    {% if addy.first_name == None or not addy.first_name %}
                    <h4 class="shipping_to_name">{{ user }}</h4>
                    {% else %}
                    <h4 class="shipping_to_name">{{ addy.first_name }} {{ addy.last_name }}
                    </h4>
                    {% endif %}
                    <h4 class="shipping_street_address">{{ addy.address_line }}</h4>
                    {% if address.address_line2 %}
                    <h4 class="shipping_street_address">{{ addy.address_line2 }}</h4>
                    {% endif %}
                    {% if addy.apartment_suite_number and addy.apartment_suite_number != "N/A"%}
                    <h4 class="shipping_street_address">
                        Apt/Ste: {{ addy.apartment_suite_number }}
                    </h4>
                    {% endif %}
                    <h4 class="shipping_city_state_zip">{{ addy.town_city }}, {{ addy.state }}
                        {{ addy.postcode}}</h4>
                    {% if addy.phone_number %}
                    <h4 class="shipping_phone_number">{{ addy.phone_number }}</h4>
                    {% else %}
                    <h4 class="shipping_phone_number">{{ user.mobile_phone }}</h4>
                    {% endif %}
                </label><br>
                {% endfor %}
                <button type="submit" class="address_change_button_long use-selected-address">Use Selected
                    Address</button>
            </form>
        </div>

        <!-- Add New Address Tab -->
        <form action="{% url 'pop_up_payment:billing_address' %}" method="POST" class="billing_address_content"
            id="new-tab">
            {% csrf_token %}
            <!-- Reuse the same form or a seperate one -->
            <div class="ship_to_name_update_modal_container">
                <div class="billing_address_inputs">
                    {{ edit_address_form.prefix }}
                </div>
                <div class="personal_info_names_container">
                    <div class="personal_info_add_medium">
                        {{ edit_address_form.first_name }}
                    </div>
                    <div class="personal_info_add_medium">
                        {{ edit_address_form.middle_name}}
                    </div>
                    <div class="personal_info_add_medium">
                        {{ edit_address_form.last_name }}
                    </div>
                </div>
                <div class="billing_address_inputs">
                    {{ edit_address_form.suffix }}
                </div>
            </div>
            <div class="ship_to_address_update_modal_container">
                <div class="personal_info_add_long">
                    {{ edit_address_form.address_line }}
                </div>
                <div class="personal_info_add_long">
                    {{ edit_address_form.address_line2 }}
                </div>
                <div class="personal_info_add_small">
                    {{ edit_address_form.apartment_suite_number }}
                </div>
                <div class="personal_info_city_state_zip_container">
                    <div class="personal_info_add_medium">
                        {{ edit_address_form.town_city }}
                    </div>
                    <div class="personal_info_choice_inputs">
                        {{ edit_address_form.state}}
                    </div>
                    <div class="personal_info_add_small">
                        {{ edit_address_form.postcode }}
                    </div>
                </div>
                <div class="billing_address_delivery_instructions">
                    {{ edit_address_form.delivery_instructions }}
                </div>
            </div>
            <div class="default_billing_address_container">
                {{ edit_address_form.is_default_billing.label }}
                {{ edit_address_form.is_default_billing }}
            </div>
            <input type="submit" class="address_change_button_long" value="Save New Address">
        </form>
    </div>
</div>
{% endif %}
{% endblock %}

templates/payment/canceled.html
{% extends "layout.html" %}
{% load static %}
{% load humanize %}

{% block title %}
Payment
{% endblock %}

{% block main %}
<section class="product_buy_section container">
    {% if user.is_authenticated %}
    <div class="section_container">
        <div class="page_title">
            <h2>Payment Not Successful</h2>
        </div>

    </div>
    {% endif %}

</section>

{% endblock %}

templates/payment/placed_order.html
{% extends "layout.html" %}
{% load static %}


{% block title %}
Order Placed
{% endblock %}

{% block main %}

<div class="login_section_container">
    <div class="page_title">
        <h2>Order Placed</h2>
    </div>
    <div class="order_placed_container">
        <div class="order_placed_status_contaner">
            <h3>Thanks {{ user.first_name }}!</h3>
            <p>We've received your order and are confirming your payment.</p>
            <p>You will receive an email shortly confirming your order</p>
            <p>Order #{{ order_id }}</p>
        </div>
    </div>
    <div class="order_placed_container">
        <div class="order_placed_status_contaner">
            <h3>Get Notified When These Items Available</h3>
            <p>Just Press "Notify Me"</p>
        </div>
    </div>

    <div class="cs_container">
        {% if product %}
        {% for prod in product %}
        <div class="cs_display_container">
            <div class="rectangle_image_container">
                <div class="background_rectangle"></div>
                {% for image in prod.product_image.all %}
                {% if image.is_feature %}
                <img class="img_fluid_cs" alt="{{ image.alt_text }}" src="{{ image.image }}"
                    alt="{{ image.image.alt_text}}" />
                {% endif %}
                {% endfor %}
            </div>

            <div class="cs_desc_container">
                {% for spec in prod.popupproductspecificationvalue_set.all|slice:"2:3" %}
                <h3>{{ spec }}</h3>
                {% endfor %}
                <h3>{{ prod.product_title }}</h3>
                <h3>{{ prod.secondary_product_title}}</h3>
            </div>
            <div class="cs_button_container">
                {% if user.is_authenticated and prod in user.prods_on_notice_for.all %}
                <button class="button_medium notify-me-button" data-product-id="{{ prod.id }}" data-interested="true">On
                    Notice ❤️</button>
                {% else %}
                <button class="button_medium notify-me-button" data-product-id="{{ prod.id }}"
                    data-interested="false">Notify
                    Me
                </button>
                {% endif %}
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h4>Nothing to display</h4>
        {% endif %}
    </div>
</div>
<script>
    var STRIPE_PUBLIC_KEY = '{{ STRIPE_PUBLIC_KEY }}'
    var CSRF_TOKEN = '{{ csrf_token }}';
</script>
{% endblock %}

templates/payment/shipping_address.html
{% extends "layout.html" %}
{% load static %}
{% load humanize %}

{% block title %}
Payment
{% endblock %}

{% block main %}
<section class="product_buy_section container">
    {% if user.is_authenticated %}
    <div class="section_container">
        <div class="page_title">
            <h2>Shipping Address</h2>
        </div>
        <div class="billing_address_container">
            <!-- Button Navigation -->
            <div class="billing_address_buttons">
                <button type="button" class="billing_address_button activated" data-tab="edit-tab">Edit
                    Address</button>
                <button type="button" class="billing_address_button" data-tab="choose-tab">Choose
                    Other</button>
                <button type="button" class="billing_address_button" data-tab="new-tab">Add
                    new</button>
            </div>
            <!-- Edit Address Tab -->
            <form action="{% url 'pop_up_payment:shipping_address' %}" method="post"
                class="billing_address_content activated" id="edit-tab">
                {% csrf_token %}

                <input type="hidden" name="address_id" value="{{ address_form.instance.id }}">

                <div class="ship_to_name_update_modal_container">
                    <div class="billing_address_inputs">
                        {{ address_form.prefix }}
                    </div>
                    <div class="personal_info_names_container">
                        <div class="personal_info_add_medium">
                            {{ address_form.first_name }}
                        </div>
                        <div class="personal_info_add_medium">
                            {{ address_form.middle_name}}
                        </div>
                        <div class="personal_info_add_medium">
                            {{ address_form.last_name }}
                        </div>
                    </div>
                    <div class="billing_address_inputs">
                        {{ address_form.suffix }}
                    </div>
                </div>
                <div class="ship_to_address_update_modal_container">
                    <div class="personal_info_add_long">
                        {{ address_form.address_line }}
                    </div>
                    <div class="personal_info_add_long">
                        {{ address_form.address_line2 }}
                    </div>
                    <div class="personal_info_add_small">
                        {{ address_form.apartment_suite_number }}
                    </div>
                    <div class="personal_info_city_state_zip_container">
                        <div class="personal_info_add_medium">
                            {{ address_form.town_city }}
                        </div>
                        <div class="personal_info_choice_inputs">
                            {{ address_form.state}}
                        </div>
                        <div class="personal_info_add_small">
                            {{ address_form.postcode }}
                        </div>
                    </div>

                    <div class="billing_address_delivery_instructions">
                        {{ address_form.delivery_instructions }}
                    </div>
                </div>
                <div class="default_billing_address_container">
                    {{ edit_address_form.is_default_shipping.label }}
                    {{ edit_address_form.is_default_shipping }}
                </div>
                <input class="button_medium" type="submit" value="Save"></input>
            </form>

            <div class="billing_add_address_tab billing_address_content" id="choose-tab">
                <p>Select from Your Saved Addresses:</p>
                <form action="{% url 'pop_up_payment:shipping_address' %}" class="select_address_form" method="POST">
                    {% csrf_token %}
                    {% for addy in saved_addresses %}
                    <label>
                        <input type="radio" name="selected_address" value="{{ addy.id }}">
                        {% if addy.first_name == None or not addy.first_name %}
                        <h4 class="shipping_to_name">{{ user }}</h4>
                        {% else %}
                        <h4 class="shipping_to_name">{{ addy.first_name }} {{ addy.last_name }}
                        </h4>
                        {% endif %}
                        <h4 class="shipping_street_address">{{ addy.address_line }}</h4>
                        {% if address.address_line2 %}
                        <h4 class="shipping_street_address">{{ addy.address_line2 }}</h4>
                        {% endif %}
                        {% if addy.apartment_suite_number and addy.apartment_suite_number != "N/A"%}
                        <h4 class="shipping_street_address">
                            Apt/Ste: {{ addy.apartment_suite_number }}
                        </h4>
                        {% endif %}
                        <h4 class="shipping_city_state_zip">{{ addy.town_city }}, {{ addy.state }}
                            {{ addy.postcode}}</h4>
                        {% if addy.phone_number %}
                        <h4 class="shipping_phone_number">{{ addy.phone_number }}</h4>
                        {% else %}
                        <h4 class="shipping_phone_number">{{ user.mobile_phone }}</h4>
                        {% endif %}
                    </label><br>
                    {% endfor %}
                    <button type="submit" class="address_change_button_long use-selected-address">Use Selected
                        Address</button>
                </form>
            </div>

            <!-- Add New Address Tab -->
            <form action="{% url 'pop_up_payment:shipping_address' %}" method="POST" class="billing_address_content"
                id="new-tab">
                {% csrf_token %}
                <!-- Reuse the same form or a seperate one -->
                <div class="ship_to_name_update_modal_container">
                    <div class="billing_address_inputs">
                        {{ edit_address_form.prefix }}
                    </div>
                    <div class="personal_info_names_container">
                        <div class="personal_info_add_medium">
                            {{ edit_address_form.first_name }}
                        </div>
                        <div class="personal_info_add_medium">
                            {{ edit_address_form.middle_name}}
                        </div>
                        <div class="personal_info_add_medium">
                            {{ edit_address_form.last_name }}
                        </div>
                    </div>
                    <div class="billing_address_inputs">
                        {{ edit_address_form.suffix }}
                    </div>
                </div>
                <div class="ship_to_address_update_modal_container">
                    <div class="personal_info_add_long">
                        {{ edit_address_form.address_line }}
                    </div>
                    <div class="personal_info_add_long">
                        {{ edit_address_form.address_line2 }}
                    </div>
                    <div class="personal_info_add_small">
                        {{ edit_address_form.apartment_suite_number }}
                    </div>
                    <div class="personal_info_city_state_zip_container">
                        <div class="personal_info_add_medium">
                            {{ edit_address_form.town_city }}
                        </div>
                        <div class="personal_info_choice_inputs">
                            {{ edit_address_form.state}}
                        </div>
                        <div class="personal_info_add_small">
                            {{ edit_address_form.postcode }}
                        </div>
                    </div>
                    <div class="billing_address_delivery_instructions">
                        {{ edit_address_form.delivery_instructions }}
                    </div>
                </div>
                <div class="default_billing_address_container">
                    {{ edit_address_form.is_default_shipping.label }}
                    {{ edit_address_form.is_default_shipping }}
                </div>
                <input type="submit" class="address_change_button_long" value="Save New Address">
            </form>
        </div>
    </div>
    {% endif %}
</section>
{% endblock %}

templates/payment/success.html
{% extends "layout.html" %}
{% load static %}
{% load humanize %}

{% block title %}
Payment
{% endblock %}

{% block main %}
<section class="product_buy_section container">
    {% if user.is_authenticated %}
    <div class="section_container">
        <div class="page_title">
            <h2>Payment Success</h2>
        </div>

    </div>
    {% endif %}

</section>

{% endblock %}